name: CI/CD Pipeline
on: [push, workflow_dispatch] # workflow_dispatch позволит запускать вручную кнопкой

jobs:
  run-everything:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Явно разрешаем запись
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '24' }
          
      - name: Install
        run: npm install telegraf @supabase/supabase-js

      - name: Run Bot
        run: node bot.js &
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Inject Secrets
        run: |
          sed -i "s|URL_SUPABASE|${{ secrets.SUPABASE_URL }}|g" index.html
          sed -i "s|KEY_SUPABASE|${{ secrets.SUPABASE_KEY }}|g" index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          
